### ISSUE TITLE
Would it be possible to give an example of how to use TCACoordinators with a TabView at the top level?

### ISSUE THREAD

**Issue by ChrisG-HGH** [johnpatrickmorgan/TCACoordinators#1]
Thanks for creating this library.  I'm learning The Composable Architecture and got stuck on how to do multi-level/nested navigation, so the TCACoordinators are a great help.  My home view will have a TabView with 3 tabs, and each of those 3 tabs will have a set of nested navigation views.  I can't quite figure out how to incorporate TabView with TCACoordinators. Would you please be kind enough to take the time to show a short example? 

Many thanks!

**Comment by johnpatrickmorgan** [comment]
Thanks! I would have a separate coordinator view (with its own state, action and reducer) for each of the tabs, and they would each use a `NavigationStore` in their body. I've updated the example code to use a tab view at the top level - hope that helps!
