### ISSUE TITLE
Importing TCACoordinators doesn't import FlowStacks

### ISSUE THREAD

**Issue by jshier** [johnpatrickmorgan/TCACoordinators#10]
For instance, since `Route` comes from FlowStacks, using it as part of a coordinator's definition can't find the symbol without the separate import. I *think* the proper fix is a `@_exported import FlowStacks` from one of the `TCACoordinators` files, but I'm not entirely sure.

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this: I wasn't aware of `@_exported` but it would be really useful in this case.

**Comment by johnpatrickmorgan** [comment]
This is now available in v0.1.1.
