### ISSUE TITLE
The Alert feature not working

### ISSUE THREAD

**Issue by liunina** [johnpatrickmorgan/TCACoordinators#12]
".alert(self.store.scope(state: \.alert), dismiss: .dismissAlert)"

not working.

[Presentation] Attempt to present <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x7f82f4145220> on <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentV8HelloArt11PadRootViewGVS_30_EnvironmentKeyWritingModifierGSqC12PartialSheet19PartialSheetManager____: 0x7f82f4113dc0> (from <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVVS_22_VariadicView_Children7ElementVS_24NavigationColumnModifier__: 0x7f82f4316400>) which is already presenting <AlertX.AlertXViewController: 0x7f82f582b800>.

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue. Are you able to describe the issue in more detail and/or share a minimal reproducible example please? I've tested a few setups but have not hit any problems. Thanks

**Comment by liunina** [comment]
> Thanks for raising this issue. Are you able to describe the issue in more detail and/or share a minimal reproducible example please? I've tested a few setups but have not hit any problems. Thanks

my bad..

struct NumberDetailState: Equatable {
    static func == (lhs: NumberDetailState, rhs: NumberDetailState) -> Bool {
        return lhs.id == rhs.id (no working)
        **return lhs.id == rhs.id && lhs.alert?.id == rhs.alert?.id**
    }
    
  
    let id: UUID
  var number: Int
    var alert: AlertState<NumberDetailAction>?
}

**Comment by johnpatrickmorgan** [comment]
Thanks, glad you sorted it.
