### ISSUE TITLE
10th CaseLet setup got problem

### ISSUE THREAD

**Issue by lmw4051** [johnpatrickmorgan/TCACoordinators#16]
When I wanted to add the 10th CaseLet in coordinator view, the compiler threw errors:
Cannot convert value of type '() -> TupleView<(CaseLet<ScreenState, ScreenAction,

I thought this is because we can't have 10 subviews in one container, but after using Group the problems still exists. Any idea to solve this issue?

**Comment by johnpatrickmorgan** [comment]
Thanks @lmw4051 - I don't believe this issue relates to this library, but would you mind sharing the code where you set up the TCARouter, and I'll try to help? Thanks.

**Comment by lmw4051** [comment]
Thanks for the reply. I think that's the subview limit from SwiftUI.

I created a project for reproducing the issue in a simpler way, I know it's not normal. 

The situation is quite similar including onboarding flow and some side menu push, so the CaseLet setup will be more than 9, the 10th one will show the compiler error.
[CoordinatorTest.zip](https://github.com/johnpatrickmorgan/TCACoordinators/files/8478170/CoordinatorTest.zip)

You mentioned about "Composing child coordinators" in the page, could you give me an example about how to apply that? Maybe that is the way to solve the problem.

**Comment by johnpatrickmorgan** [comment]
Thanks for sharing. The limitation you're hitting is not related to SwiftUI's ViewBuilder (hence why Group won't help). It's that `SwitchStore` (from the `swift-composable-architecture` library) only has overloads for up to 10 cases. There's some discussion and workarounds here (from when the limit was 5):

https://github.com/pointfreeco/swift-composable-architecture/issues/602

But it may also be useful to break up your navigation flow into multiple coordinators. I'll try to write up more detail on how to use child coordinators to achieve that.

**Comment by lmw4051** [comment]
> when the limit was 5

Really thanks for the info you shared and looking forward to your child coordinator implementations as well, thanks in advance.

**Comment by lmw4051** [comment]
I finally found the solution as below.

```Swift
struct CoordinatorView: View {
  let store: Store<CoordinatorState, CoordinatorAction>
  
  var body: some View {
    TCARouter(store) { screen in
      Group {
        SwitchStore(screen) {
          CaseLet(
            state: /ScreenState.initial,
            action: ScreenAction.initial,
            then: InitialView.init
          )
          CaseLet(
            state: /ScreenState.signUp,
            action: ScreenAction.signUp,
            then: SignUpView.init
          )
          CaseLet(
            state: /ScreenState.login,
            action: ScreenAction.login,
            then: LoginView.init
          )

	 Other CaseLet()
          Default {}
        }
        
        SwitchStore(screen) {
          CaseLet(
            state: /ScreenState.sample,
            action: ScreenAction.sample,
            then: SampleView.init
          )
          Other CaseLet()
          Default {}
        }
      }
    }
  }
}
```

**Comment by johnpatrickmorgan** [comment]
Awesome, glad you found the solution, thanks for updating here.
