### ISSUE TITLE
How to cancel in-flight effect when we replace stack?

### ISSUE THREAD

**Issue by josephktcheung** [johnpatrickmorgan/TCACoordinators#21]
Hi,

We're replacing route stack in our app, and we'd like to know if there's an efficient way to cancel all in-flight effects in the previous route stack.

Example Coordinator:

```swift
let coordinatorReducer = Reducer { state, action, environment in
        case let .modeChanged(mode):
            switch mode {
            case .one:
                state.routes = [.root(.one(.init()), embedInNavigationView: true)]
            case .two:
                state.routes = [.root(.two(.init()), embedInNavigationView: true)]
            default:
                break
            }
}
```

From the documentation it can cancel in-flight effect when that screen is popped or dismissed https://github.com/johnpatrickmorgan/TCACoordinators#cancellation-of-in-flight-effects-on-dismiss, however replacing route stack means we need to cancel all in-flight effects inside the route stack at once

e.g. last route has pushed 3 screens (A -> B -> C) and replacing it to something new (D)

```
[A -> B -> C] -> [D]
```

How should I cancel the in-flight effect(s) of screen A, B and C?

Best,
Joseph

**Comment by johnpatrickmorgan** [comment]
Hi @josephktcheung! Are you using `IdentifiedCoordinatorState` or `IndexedCoordinatorState`?

If your state conforms to `IdentifiedCoordinatorState`, then each screen's effects are tagged for cancellation using the screen's `id`. So when you change from `[A -> B -> C]` to  `[D]`, all of A, B and C's in-flight effects should be cancelled automatically.

If your state conforms to `IndexedCoordinatorState`, then each screen's effects are tagged for cancellation using the screen's `index`. So when you change from `[A -> B -> C]` to  `[D]`, B and C's in-flight effects should be cancelled automatically, but not A's, as that index has not been removed.

**Comment by josephktcheung** [comment]
Hi @johnpatrickmorgan we are using the indexed one. How do we cancel in this case? Or should we change all of our coordinator state to identified because of this issue?

**Comment by johnpatrickmorgan** [comment]
@josephktcheung Sorry for the late response. If you want to continue using `IndexedCoordinatorState`, you would have to manage the cancellation of in-flight effects yourself. I think it's better to use `IdentifiedCoordinatorState` if you want effects to be cancelled when you replace screens. I'll make the README a bit clearer in that regard.

**Comment by johnpatrickmorgan** [comment]
Hi @arisupriatna14 - I've added an example to the repo of how I would approach a [simple authentication flow](https://github.com/johnpatrickmorgan/TCACoordinators/blob/2461e380bdd50da93cf64375e059c79438c90749/TCACoordinatorsExample/TCACoordinatorsExample/Game/AppCoordinator.swift).

**Comment by arisupriatna14** [comment]
Thank you @johnpatrickmorgan. It's helping me. :)
