### ISSUE TITLE
How to handle SwitchStore more than 9 screens

### ISSUE THREAD

**Issue by arisupriatna14** [johnpatrickmorgan/TCACoordinators#24]
Hi @johnpatrickmorgan 

After restructuring my project using TCACoordinator for navigation, I have some problem when I'm using TCACoordinator.
The problem is when I have screen more than 9 and when add new screen into SwitchStore is shown an error like this:

`
Cannot convert value of type '() -> TupleView<(CaseLet<ScreenState, ScreenAction, AccountState, AccountAction, AccountView>, CaseLet<ScreenState, ScreenAction, EditProfileState, EditProfileAction, EditProfileView>, CaseLet<ScreenState, ScreenAction, ListMemberFamilyState, ListMemberFamilyAction, ListMemberFamilyView>, CaseLet<ScreenState, ScreenAction, EditMemberFamilyState, EditMemberFamilyAction, EditMemberFamilyView>, CaseLet<ScreenState, ScreenAction, AccountSettingState, AccountSettingAction, AccountSettingsView>, CaseLet<ScreenState, ScreenAction, ChangePasswordState, ChangePasswordAction, ChangePasswordView>, CaseLet<ScreenState, ScreenAction, LanguageSettingState, LanguageSettingAction, LanguageSettingView>, CaseLet<ScreenState, ScreenAction, AddMemberFamilyState, AddMemberFamilyAction, AddMemberFamilyView>, CaseLet<ScreenState, ScreenAction, FullProfileDataState, FullProfileDataAction, FullProfileDataView>, CaseLet<ScreenState, ScreenAction, ListMyAddressState, ListMyAddressAction, ListMyAddressView>)>' to expected argument type '() -> TupleView<(CaseLet<ScreenState, ScreenAction, AccountState, AccountAction, AccountView>, CaseLet<ScreenState, ScreenAction, EditProfileState, EditProfileAction, EditProfileView>, CaseLet<ScreenState, ScreenAction, ListMemberFamilyState, ListMemberFamilyAction, ListMemberFamilyView>, CaseLet<ScreenState, ScreenAction, EditMemberFamilyState, EditMemberFamilyAction, EditMemberFamilyView>, CaseLet<ScreenState, ScreenAction, AccountSettingState, AccountSettingAction, AccountSettingsView>, CaseLet<ScreenState, ScreenAction, ChangePasswordState, ChangePasswordAction, ChangePasswordView>, CaseLet<ScreenState, ScreenAction, LanguageSettingState, LanguageSettingAction, LanguageSettingView>, CaseLet<ScreenState, ScreenAction, AddMemberFamilyState, AddMemberFamilyAction, AddMemberFamilyView>, CaseLet<ScreenState, ScreenAction, FullProfileDataState, FullProfileDataAction, FullProfileDataView>, Default<_>)>'
`

Can you help me how to solve this issue?

Thanks. 🙏

**Comment by johnpatrickmorgan** [comment]
For anyone else that encounters this  issue, please see #16.
