### ISSUE TITLE
Without `WithViewStore(store)` around TCARouter, initial state is replayed when dismissing sheet or cover

### ISSUE THREAD

**Issue by salqueng** [johnpatrickmorgan/TCACoordinators#26]
## What did I do.

The example application uses `WithViewStore(store) { ... }` on the root body, which wraps TabView & TCARouter.
This is not good for performance, especially for large applications, which have lots of states and actions.
To achieve better performance, I removed WithViewStore on root and ran the example.

It worked fine for pushing, opening new sheet, and increasing numbers, but I found something weird when I pressed `Go Back` on a sheet - It replays the initial old state.

1. Start the modified app on simulator (WithViewStore on root is removed)
   https://github.com/holixfactory/TCACoordinators/tree/replay-bug
3. Press `start`
4. Press `0`
5. Press `Show Double` to open a sheet
6. Press `Increment` - The number becomes 1
7. To see what happens carefully, Turn on `Slow Animations`
8. Press `Go Back`
9. Observe what happens to the "Number" section

## What is expected.

The sheet should be dismissed without any visual changes - "Number" remains as 1

## What actually happened.
The sheet was dismissed with a visual change - "Number" became 0
It looks like that TCARouter replays the old initial state.

https://user-images.githubusercontent.com/5074074/175615686-369d2f2b-b5c6-4dce-b52c-fd8cf3cdae88.mp4

## Additional Context

This is because `scopedStore` of `TCARouter` uses initial screen when the screen for the index is nil. It must use the latest cached version of the screen for index.

This issue is very similar to https://github.com/pointfreeco/swift-composable-architecture/issues/496, which was fixed by https://github.com/pointfreeco/swift-composable-architecture/pull/667.

I'll post a PR fixing this issue.

**Comment by johnpatrickmorgan** [comment]
Released in [v0.2.0](https://github.com/johnpatrickmorgan/TCACoordinators/releases/tag/0.2.0)
