### ISSUE TITLE
How can we routes to check existing views?

### ISSUE THREAD

**Issue by lmw4051** [johnpatrickmorgan/TCACoordinators#29]
Can we use "var routes: [Route<ScreenState>]" to check existing views we pushed to the stack before? If so, is there any example code I can follow with?

**Comment by johnpatrickmorgan** [comment]
Hi @lmw4051! Yes the routes array can be inspected at runtime. For example, a lot of the [utility methods](https://github.com/johnpatrickmorgan/FlowStacks/blob/main/Sources/FlowStacks/RoutableCollection%2Butilities.swift) exposed on arrays of routes inspect the current state of the array.

**Comment by lmw4051** [comment]
> Hi @lmw4051! Yes the routes array can be inspected at runtime. For example, a lot of the [utility methods](https://github.com/johnpatrickmorgan/FlowStacks/blob/main/Sources/FlowStacks/RoutableCollection%2Butilities.swift) exposed on arrays of routes inspect the current state of the array.

Thanks for the reply, but at the moment I still don't know how to check the existing views inside the routes. Can you give me an example? Thanks in advance.

**Comment by lmw4051** [comment]
> I'm a bit unsure what you want to achieve but you can iterate through the routes and access each route's screen (e.g. `MyScreen` in a `[Route<MyScreen>]`:
> 
> ```swift
> for route in routes {
>   print(route.screen)
> }
> ```
> 
> Or inspect the final screen:
> 
> ```swift
> print(routes.last?.screen)
> ```



> I'm a bit unsure what you want to achieve but you can iterate through the routes and access each route's screen (e.g. `MyScreen` in a `[Route<MyScreen>]`:
> 
> ```swift
> for route in routes {
>   print(route.screen)
> }
> ```
> 
> Or inspect the final screen:
> 
> ```swift
> print(routes.last?.screen)
> ```

Thanks for the reply. What I want to achieve is to check the existing views which has been pushed before, like in UIKit, we can use navigationController.viewControllers to inspect the viewControllers in the stack or not.

So, we can use screen comparison to achieve the function mentioned above? 

Such as if route.screen == ??

**Comment by johnpatrickmorgan** [comment]
Yes, you can check what views have been pushed before, e.g.:

```swift
if let lastScreen = routes.last?.screen {
  switch screen {
  case .home:
    print("Most recently shown screen is home")
  case .profile(let username):
    print("Most recently shown screen is \(username)'s profile")
  }
}
```

**Comment by lmw4051** [comment]
> Yes, you can check what views have been pushed before, e.g.:
> 
> ```swift
> if let lastScreen = routes.last?.screen {
>   switch screen {
>   case .home:
>     print("Current screen is home")
>   case .profile(let username):
>     print("Current screen is \(username)'s profile")
>   }
> }
> ```

Thanks for the reply.
