### ISSUE TITLE
Previous State values being restored when transitioning back from detail screen

### ISSUE THREAD

**Issue by tyler927** [johnpatrickmorgan/TCACoordinators#34]
Not sure the best way to describe this issue, so I am just going to describe what is happening in my app.

I have a screen to display a list of favorites that are stored in CoreData. From this list you can tap on an item to go to its detail page, from there, you can unfavorite the item. When you then go back to the list view, it updates the list from the `onAppear` instance method. The list correctly updates with that item being removed from favorites. But then roughly 0.5 later, the list updates again, this time with the old favorited item still in the list. If you then refresh the screen, or even put a 0.5 delay after `onAppear` is called, the correct list is shown, without the old favorited item. 

The weird part is though, when the second (unintended) update to the screen happens. The reducer is not being called again, and even the items in the state object `didSet` is not being called again. So it's almost seems like the previous state is just being restored by TCACoordinators. 

I've concluded this is not a CoreData issue by using other methods such as a singleton, or user defaults to save the values. I also don't believe this to be a regular TCA issue, as I cannot reproduce when using just regular `NavigationLinks`. 

Since it's a bit of code to show here, I made a small sample project demonstrating the issue that is 100% reproducible. 
[CoordBug.zip](https://github.com/johnpatrickmorgan/TCACoordinators/files/9619240/CoordBug.zip)

Screen recording of my sample app I made demonstrating this. 
The label should be "changed from detail" but reverts back to "not set".
![IMB_OKTG2K](https://user-images.githubusercontent.com/10719676/191579019-c23d1ae7-1526-49be-aa7e-53d74f748b05.GIF)

**Comment by johnpatrickmorgan** [comment]
Thanks @tyler927 for raising this issue and for the great sample project. I can at least see what's happening but I'm not yet sure what the fix should be. When you pop back using the built-in back button, first the `onAppear` closure of the initial screen is called, which causes the initial screen to pull the new value from the environment into its state (all good so far). After that, the NavigationLink (hidden away in `FlowStacks` code) has its `isActive` binding reset to false, which `FlowStacks.Node` uses to pop the last item off the routes array, to keep everything in sync. In theory, this should work correctly, but it seems the `Node` has a stale version of the routes array, without the initial screen's updated state, so when it pops the last route, it also inadvertently resets the initial screen's state. 

I'll try and figure out the correct way to fix this issue...

**Comment by salqueng** [comment]
Hello @tyler927. I have noticed the problem few months ago, and I created the patch but didn't create any pull request.

Could you try this branch and tell me if it fixes the problem or not?
https://github.com/holixfactory/TCACoordinators/tree/0.2.0-fix

**Comment by tyler927** [comment]
@salqueng that works! Thanks for that. @johnpatrickmorgan have you had a chance to look at that as a possible fix?

**Comment by johnpatrickmorgan** [comment]
Thanks a lot @salqueng. It looks like your change is equivalent to removing the `removeDuplicates: { routes($0).map(\.style) == routes($1).map(\.style) }` argument in the body of `TCARouter`. Doing so also fixes the issue, but the `removeDuplicates` was added in #20 as a performance improvement, so I'm wondering if it's possible to fix the issue without losing those performance benefits.

**Comment by johnpatrickmorgan** [comment]
Actually @salqueng I think your fix maintains those performance benefits after all. When testing with your change, I didn't see the first screen being re-rendered when there were state updates to the second screen, and I did when removing the `removeDuplicates` argument.

@dannyhertz I wonder if you have any objection to @salqueng's [proposed change](https://github.com/johnpatrickmorgan/TCACoordinators/compare/main...holixfactory:TCACoordinators:0.2.0-fix) as far as it might affect #20? Thanks

**Comment by johnpatrickmorgan** [comment]
Thanks very much @salqueng - I've merged your changes, which fix this issue. Released as v0.2.2.

**Comment by tyler927** [comment]
Thanks again @salqueng and @johnpatrickmorgan 👍
