### ISSUE TITLE
Do you have plans to support ReducerProtocol?

### ISSUE THREAD

**Issue by dp221125** [johnpatrickmorgan/TCACoordinators#38]
Hello.

First of all, I've been using it well and thank you.

So,
There was a big update recently at TCA.
It is [ReducerProtocol](https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.43.0).

So I wonder if you have any plans to support.
If you have a plan, would you tell me the timing?

**Comment by johnpatrickmorgan** [comment]
Hi @dp221125! I do plan to migrate across to `ReducerProtocol`, and I've started making the changes, but don't have a lot of spare time to dedicate to it, so it's hard to say when it will be ready - hopefully within the next month. Sorry I can't be more definite.

**Comment by johnpatrickmorgan** [comment]
Hi @dp221125, I've now updated to ReducerProtocol in version 0.3.0. Please see the README for the new API.

**Comment by dp221125** [comment]
@johnpatrickmorgan Thank you for the quick update.
