### ISSUE TITLE
How to dismiss a view and present a new one ?

### ISSUE THREAD

**Issue by hilalalhakani** [johnpatrickmorgan/TCACoordinators#42]
Hello, 
I stumbled upon an issue where I want to dismiss my sign-in screen and present the signup screen and vice versa. 
The problem is that I didn't know how to wait until the screen is dismissed to present a new one.
Below is what I did to dismiss one screen and present the second one. 

```
  case .routeAction(_, .signIn(.signUpPressed)):
    state.routes.dismiss(count: 1)
    state.routes.presentCover(.signUp(.init()), embedInNavigationView: true)
    return .none

    case .routeAction(_, .signUp(.signInPressed)):
    state.routes.dismiss(count:1)
    state.routes.presentCover(.signIn(.init()), embedInNavigationView: true)
    return .none
```

https://user-images.githubusercontent.com/24891448/213871718-29795a54-959a-4d10-92f3-8e51a01a7cad.mp4

As per the attached video, there is no animation when dismissing/presenting any screen.

**Comment by johnpatrickmorgan** [comment]
Hi @hilalalhakani, thanks for raising this issue. The reason you see no animation is that after you dismiss and present, the navigation stack has the same structure, the only thing that has changed is the content of the presented view (sign-in vs sign-up). 

If you want to see the dismiss animation and then the present animation, you will need to separate those two state updates. In particular, you will need enough of a delay between the two for the dismiss animation to complete (650 milliseconds seems to be enough). SwiftUI doesn't provide a hook to know when the animation is complete, so a hacky way to achieve it would be with a delay:

```swift
case .routeAction(_, .signIn(.signUpPressed)):
  state.routes.dismiss()

  var newRoutes = state.routes
  newRoutes.presentCover(.signUp(.init()), embedInNavigationView: true)
    
  return Effect(value: .updateRoutes(newRoutes))
    .delay(for: .milliseconds(650), scheduler: DispatchQueue.main)
    .eraseToEffect()
```

Alternatively, you could try restructuring your navigation flow to avoid this situation, e.g. either present sign-in/sign-up or navigate back to it if it's already in the routes:

```swift
case .routeAction(_, .signIn(.signUpPressed)):
  let goBackSucceeded = state.routes.goBackTo(where: {
    if case .signUp = $0 { return true }
    return false
  })
  if !goBackSucceeded {
    state.routes.presentCover(.signUp(.init()), embedInNavigationView: true)
  }
  return .none

case .routeAction(_, .signUp(.signInPressed)):
  let goBackSucceeded = state.routes.goBackTo(where: {
    if case .signIn = $0 { return true }
    return false
  })
  if !goBackSucceeded {
    state.routes.presentCover(.signIn(.init()), embedInNavigationView: true)
  }
  return .none
```

**Comment by hilalalhakani** [comment]
Thanks for your response @johnpatrickmorgan. 
I will go with the second approach. 
Great job with the library
