### ISSUE TITLE
Present sheet and next sheet

### ISSUE THREAD

**Issue by erykmroczko** [johnpatrickmorgan/TCACoordinators#44]
Hello,

TCA coordinators are incredible. But I have a major problem - I presentSheet from coordinator, and when user taps buttons next sheet is presented, while previous is not dismissed. Right before removing the state of previous sheet is changed. But when I'm removing last sheet from stack (no matter if I use remove or dismiss) previous sheet is going back to the state it was in before that second sheet was presented. I can embed code if it is necessary, but maybe someone know what I could I done already so it's not working. 

Cheers!

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this @erykmroczko ! This sounds like issue #34, which was thought to be fixed with #35. Please could you confirm you're using a TCACoordinators version higher than `0.2.2`. If so, are you able to share any code that reproduces the issue please? Thanks!
