### ISSUE TITLE
Can't chain multiple actions when using routes with IdentifiedArray

### ISSUE THREAD

**Issue by ZachJiroun** [johnpatrickmorgan/TCACoordinators#49]
I'm getting the following compiler error when I try using `routeWithDelaysIfUnsupported` to chain a modal dismissal, followed by a push. I'm using an IdentifiedArray and my code is modeled after the `FormAppCoordinator` in the example project. I'm not sure why the compiler wants me to switch to an IndexedRouter to support this behavior.

`Referencing static method 'routeWithDelaysIfUnsupported' on 'EffectPublisher' requires that 'HomeCoordinator.Action' conform to 'IndexedRouterAction'`

Code is as follows:
```
                return .routeWithDelaysIfUnsupported(state.routes) {
                    $0.dismissAll()
                    $0.push(.childCoordinator)
                }
```

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue @ZachJiroun! I wonder if the compiler is giving a bad error message that hides the true error. It can be helpful to add extra type hints to the closure so that the compiler reports the true error, e.g.:

```swift
return .routeWithDelaysIfUnsupported(state.routes) { (routes: inout IdentifiedArrayOf<Route<Screen.State>>) in
  routes.dismissAll()
  routes.push(.childCoordinator)
}
```

For example, does the `.childCoordinator` case have some associated value?

**Comment by ZachJiroun** [comment]
Seems like the compiler was hiding the error message - I'm able to reproduce it using your FormAppCoordinator example as well.

This code seems to compile fine.
```
          return .routeWithDelaysIfUnsupported(state.routes) { (routes: inout IdentifiedArrayOf<Route<FormScreen.State>>) in
              routes.dismissAll()
              routes.push(.finalScreen(state.finalScreenState))
          }
```
