### ISSUE TITLE
Child coordinator and its reducers don't react on action triggers

### ISSUE THREAD

**Issue by vexonius** [johnpatrickmorgan/TCACoordinators#50]
Hi @johnpatrickmorgan, thanks for creating this awesome lib for TCA. My team and I decided to go with it with for our project, but we stumbled upon some conundrums.

Our app has RootCoordinator which routes to one of the 3 possible routes depending on logged user state. One of those states has a child coordinator that has it own flow and can push multiple screens. While presenting child coordinator with inital routes and reducer on root coordinator works, we noticed that triggering actions from child coordinator's presented screen doesnt register in screen's reducer nor in child coordinator - action only gets recognized and called in root coordinator when prinitng global store changes eg.:
```
received action:
  RootCoordinator.Action.routeAction(
    0,
    action: .onboarding(
      .routeAction(
        0,
        action: .landing(.getStarted)
      )
    )
  )
```

Root Coordinator has a RootReducer for each screen route where all store scoping is done just like ChildCoordiinator does as well (OnboardingCoordinator in example). Here is the example of root coordinator:

```swift
struct RootCoordinator: ReducerProtocol {

    struct State: Equatable, IndexedRouterState {

        static let initialState = RootCoordinator.State(
            routes: [.root(.onboarding(.initialState), embedInNavigationView: true)]
        )

        var routes: [Route<RootReducer.State>]

    }

    enum Action: IndexedRouterAction {

        case routeAction(Int, action: RootReducer.Action)
        case updateRoutes([Route<RootReducer.State>])

    }

    func reduce(into state: inout State, action: Action) -> EffectTask<Action> {
        .none
    }

    var body: some ReducerProtocol<State, Action> {
        Reduce(reduce)
            .forEachRoute {
                RootReducer()
            }
    }

}
```

My question is how should we implement screen routes and react to their actions in reducers under child coordinators? Is there an example of pushing child coordinator onto parent coordinator stack? Are we doing something wrong here? 

Thanks for your time and help! Cheers

**Comment by johnpatrickmorgan** [comment]
Hi @vexonius, thanks for raising this issue! In your example code, you define both a reduce function:

```swift
func reduce(into state: inout State, action: Action) -> EffectTask<Action> { ... }
```

...and a reducer body:

```swift
var body: some ReducerProtocol<State, Action> { ... }
```

Your reduce function satisfies a requirement of the `ReducerProtocol`, and takes precedence over the reducer body, so your reducer body is never called. See [this comment](https://github.com/pointfreeco/swift-composable-architecture/blob/ff0e4e7684e1259992c0c3c396093ab8d0f0929a/Sources/ComposableArchitecture/ReducerProtocol.swift#L116-L119) in the TCA code.

**Comment by vexonius** [comment]
Hi @johnpatrickmorgan, thanks for help! We did figure it eventually, but didn't have a clue why it is happening - thanks for the hint in the docs 😉
