### ISSUE TITLE
Hide tab bar when pushing on views from coordinator

### ISSUE THREAD

**Issue by ZachJiroun** [johnpatrickmorgan/TCACoordinators#51]
I'm having trouble getting the tab bar to hide when pushing on child views (i.e., I only want the tab bar visible at the root of each tab).

This problem is visible on the library's sample project as well. I've tried wrapping the TabView in a NavigationView but that has caused some weird behavior with child coordinators where views pushed and then automatically popped from the stack.

Any ideas on how to support this behavior? Or maybe building a custom tab bar might be the best...

**Comment by johnpatrickmorgan** [comment]
Thanks @ZachJiroun, are you using the `toolBar(.hidden)`  [modifier](https://www.hackingwithswift.com/quick-start/swiftui/how-to-hide-the-tab-bar-navigation-bar-or-other-toolbars#:~:text=SwiftUI's%20toolbar()%20modifier%20lets,hide%20after%20a%20navigation%20push.&text=If%20you%20don't%20specify,hidden)%20without%20specifying%20for%3A%20.) on the pushed view? Or is that unavailable as you're targeting below iOS 16? There are [workarounds](https://stackoverflow.com/questions/58444689/swiftui-hide-tabbar-in-subview) for earlier OS versions but I've not used any myself.

**Comment by aba-bakri** [comment]
Any solutions for iOS 15 ?
