### ISSUE TITLE
Assistance Needed migrating to TCA 1.0

### ISSUE THREAD

**Issue by timelery** [johnpatrickmorgan/TCACoordinators#56]
I have logic in my app using AnyReducer. I am struggling to figure out how to migrate it to 0.60 using TCA 1.0.

Old working logic prior to upgrade:

```
var body: some ReducerProtocol<State, Action> {
        Reduce(
            AnyReducer(Login.ScreenProvider())
                .forEachIdentifiedRoute(environment: { () })
                .withRouteReducer(AnyReducer(core)),
            environment: ()
        )
    }
```

**Comment by johnpatrickmorgan** [comment]
Hi @timelery!

It's hard to be sure from just the snippet you shared but it might be as simple as:

```swift
  var body: some Reducer<State, Action> {
    core.forEachRoute {
      Login.ScreenProvider()
    }
  }
```

But knowing more about what `core` is would help give a better answer.
