### ISSUE TITLE
Disable drag to dismiss sheet?

### ISSUE THREAD

**Issue by ivancantarino** [johnpatrickmorgan/TCACoordinators#66]
Hello 👋🏻 , 

I was wondering if there is an option to disable the drag to dismiss option of a presented `sheet`: `state.routes.presentSheet()`?

Such option would be pretty awesome, maybe including it within the `.presentSheet` interface.

**Comment by johnpatrickmorgan** [comment]
Hi!

Thanks for your question. No, there's no API in `TCACoordinators` for that. Normally, you would add `.interactiveDismissDisabled()` to the view itself - is there a reason that wouldn't work for your use case? I suppose if you wanted to be able to turn it on or off at the point of presentation, you could include it in the screen's state?

**Comment by ivancantarino** [comment]
Thanks for the reply. I forgot about that option, thanks for the hint. Indeed I can include it within the State and tweak it based on some Actions. 🙏🏻🤩
