### ISSUE TITLE
The package product 'FlowStacks' requires minimum platform version 14.0 for the iOS platform, but this target supports 13.0

### ISSUE THREAD

**Issue by Little-tale** [johnpatrickmorgan/TCACoordinators#68]
The package product 'FlowStacks' requires minimum platform version 14.0 for the iOS platform, but this target supports 13.0

And that's the error. But my project is
We are proceeding with the minimum version to 16.0.

Other library theories RealmSwift, PopUpView, and KingFisher are not expected to conflict with other packages. The TCA version is 1.10.4.

How do I solve this problem?

**Comment by johnpatrickmorgan** [comment]
Hi @Little-tale  - I'm not sure what would cause this, but it sounds like an issue with the way your project is set up. Are you able to share your project at all?

**Comment by Little-tale** [comment]
I'm going to erase the Xcode and try again
It's being applied well.
Thank you.
